// Re-export types from belief.types.ts for backward compatibility
export type {
  Content,
  Belief,
  Signal,
  SignalCollection,
  SignalDataPoint,
  HeadingData,
  ArticleData,
  ChartData,
  ChartConfig,
  RenderableChart,
  ChartDataPoints,
  ChartAxes,
  ChartMetadata,
  ContinuousData,
  ComparativeData,
  DualProbabilityData,
  HistoricalLineData,
  ObjectRankingScores,
  Category,
  LayoutType,
  FilterStatus,
  SortOption,
  ViewMode,
  ComponentVersion,
  ComponentData,
  ComponentChange,
  ComponentVariant,
  CardGroupData,
  LayoutConfig,
} from './belief.types';